### ISSUE TITLE
Resnet50 in the code to resnet10 error?

### ISSUE THREAD

**Issue by mslqing** [bardiadoosti/HOPE#18]
@bardiadoosti Hello, I changed line 12 of the hopenet.py file in the modules folder to Resnet10. The following error occurred?

Train files loaded
Validation files loaded
HopeNet is loaded
Begin training the network...
Traceback (most recent call last):
  File "HOPE.py", line 107, in <module>
    outputs2d_init, outputs2d, outputs3d = model(inputs)
  File "/home/msl/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/msl/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/msl/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/msl/code/HOPE-master/models/hopenet.py", line 21, in forward
    points2D = self.graphnet(in_features)
  File "/home/msl/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/msl/code/HOPE-master/models/graphunet.py", line 179, in forward
    X_0 = self.gconv1(X, self.A_hat)
  File "/home/msl/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/msl/code/HOPE-master/models/graphunet.py", line 44, in forward
    X = self.fc(torch.bmm(self.laplacian_batch(A_hat), X))
  File "/home/msl/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/msl/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/msl/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py", line 1372, in linear
    output = input.matmul(weight.t())
RuntimeError: size mismatch, m1: [464 x 514], m2: [2050 x 128] at /opt/conda/conda-bld/pytorch_1573049304260/work/aten/src/THC/generic/THCTensorMathBlas.cu:290

**Comment by bardiadoosti** [comment]
Hi,

Thanks for your comment. To use the current `ResNet10` which uses `BasicBlock` you should edit line 12 of `hopenet.py` file as well:
`self.graphnet = GraphNet(in_features=514, out_features=2)`

Alternatively, if you want to have 2048 features you can change the `BasicBlock` to `Bottleneck` in resnet.py line 215:
`model = ResNet(BasicBlock, [1, 1, 1, 1], num_classes=1000, **kwargs)`
